#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明
#
# Guide: https://hexo.fluid-dev.com/docs/en/guide/
# You can get more detailed help from the guide
#---------------------------


#---------------------------
# 全局
# Global
#---------------------------

# 用于浏览器标签的图标
# Icon for browser tab
# favicon: /img/fluid.png

# 用于苹果设备的图标
# Icon for Apple touch
# apple_touch_icon: /img/fluid.png

# 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名
# Title separator in browser tab, eg: article - site
# tab_title_separator: " - "

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
# Force all links to be HTTPS (applicable to HTTP mixed error)
# force_https: false

# 一些好玩的功能
# Some fun features
fun_features:
  # 为 subtitle 添加打字机效果
  # Typing animation for subtitle
  typing:
    # 在指定页面开启，不填则在所有页面开启
    # Enable in specified page, all pages by default
    # Options: home | post | tag | category | about | links | page | 404
    scope: ["home"]

  # 加载进度条
  # Progress bar when loading
  progressbar:
    enable: false

# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# Theme color, please use custom CSS to solve other colors, color schema can be inspired by the links below
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # 文章超链接字体色
  # Color of post link
  post_link_color: "#2196f3"
  post_link_color_dark: "#6ec6ff"

  # 超链接悬浮时字体色
  # Color of link when hovering
  link_hover_color: "#80d6ff"
  link_hover_color_dark: "#9be7ff"

# 指定自定义 .js 文件路径，支持列表；路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js
# Specify the path of your custom js file, support list. The path is relative to the source directory, such as `/js/custom.js` corresponding to the directory `source/js/custom.js`
custom_js: 
  - /js/custom.js
  - //identity.netlify.com/v1/netlify-identity-widget.js

# 指定自定义 .css 文件路径，用法和 custom_js 相同
# The usage is the same as custom_js
custom_css:
  - /css/custom.css
  - //at.alicdn.com/t/font_3187709_82n84dsycml.css

# 网页访问统计
# Analysis of website visitors
web_analytics:  # 网页访问统计
  enable: false

  # 百度统计的 Key，值需要获取下方链接中 `hm.js?` 后边的字符串
  # Baidu analytics, get the string behind `hm.js?`
  # See: https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376
  baidu:

  # Google 统计的 Tracking ID
  # Google analytics, set Tracking ID
  # See: https://developers.google.com/analytics/devguides/collection/analyticsjs
  google:


#---------------------------
# 页头
# Header
#---------------------------

# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title: ""

  # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
  # Navigation bar frosted glass special animation. It is an experimental feature
  ground_glass:
    enable: true

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { name: "说说", link: "/shuoshuo/", icon: "iconfont icon-comment" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }


#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  # 页脚第一行文字的 HTML，建议保留 Fluid 的链接，用于向更多人推广本主题
  # HTML of the first line of the footer, it is recommended to keep the Fluid link to promote this theme to more people
  content: '
    Powered by
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
|
    Theme
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
|
    Comment
    <a href="https://github.com/walinejs/waline" target="_blank" rel="nofollow noopener"><span>Waline</span></a>
    <br>
    Jiecs All Rights Reserved.
  '

  # 国内大陆服务器的备案信息
  # For Chinese mainland website policy, other areas keep disable
  beian:
    enable: false
    # ICP证号
    icp_text: 京ICP证123456号
    # 公安备案号，不填则只显示ICP
    police_text: 京公网安备12345678号
    # 公安备案的编号，用于URL跳转查询
    police_code: 12345678


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  # banner_img: /img/default.png

  # 头图高度，屏幕百分比
  # Height ratio of banner image
  # Available: 0 - 100
  # banner_img_height: 20

  # 头图黑色蒙版的不透明度，available: 0 - 1.0， 1 是完全不透明
  # Opacity of the banner mask, 1.0 is completely opaque
  # Available: 0 - 1.0
  # banner_mask_alpha: 0.3

  # 首页副标题的独立设置
  # Independent config of home page subtitle
  slogan:
    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text: "" # An elegant Material-Design theme for Hexo

    # 通过 API 接口作为首页副标题的内容，必须返回的是 JSON 格式，如果请求失败则按 text 字段显示，该功能必须先开启 typing 打字机功能
    # Subtitle of the homepage through the API, must be returned a JSON. If the request fails, it will be displayed in `text` value. This feature must first enable the typing animation
    api:
      enable: true

      # 请求地址
      # Request url
      url: "https://v1.hitokoto.cn/?max_length=25"

      # 从请求结果获取字符串的取值字段，最终必须是一个字符串，例如返回结果为 {"data": {"author": "fluid", "content": "An elegant theme"}}, 则取值字段为 ['data', 'content']；如果返回是列表则自动选择第一项
      # The value field of the string obtained from the response. For example, the response content is {"data": {"author": "fluid", "content": "An elegant theme"}}, the expected `keys: ['data','content']`; if the return is a list, the first item is automatically selected
      keys: ["hitokoto"]


#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  # banner_img: /img/default.png
  # banner_img_height: 70
  # banner_mask_alpha: 0.3

  # 侧边栏展示文章目录
  # Table of contents (TOC) in the sidebar
  toc:
    # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在下级标题则默认展开
    # Collapse depth. If 0, all headings collapsed. If greater than 0, it will be expanded by default if there are sub headings
    collapseDepth: 1

  # 版权声明，会显示在每篇文章的结尾
  # Copyright, will be displayed at the end of each post
  copyright:
    enable: false

  # 评论插件
  # Comment plugin
  comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis
    type: waline


#---------------------------
# 评论插件
# Comment plugins
#
# 开启评论需要先设置上方 `post: comments: enable: true`，然后根据 `type` 设置下方对应的评论插件参数
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------

# Waline
# 从 Valine 衍生而来，额外增加了服务端和多种功能
# Derived from Valine, with self-hosted service and new features
# See: https://waline.js.org/
waline:
  serverURL: 'https://blog-waline-jiesou.vercel.app'
  path: window.location.pathname
  placeholder: '说点什么吧...'
  copyright: false
  meta: ['nick', 'mail', 'link']
  requiredMeta: []
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tieba',
  'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/alus',
  'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
  'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq',
  'https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  pageSize: 10


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  # banner_img: /img/default.png
  # banner_img_height: 60
  # banner_mask_alpha: 0.3


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  # banner_img: /img/default.png
  # banner_img_height: 60
  # banner_mask_alpha: 0.3


#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  # banner_img: /img/default.png
  # banner_img_height: 80
  # banner_mask_alpha: 0.3


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  # banner_img: /img/default.png
  # banner_img_height: 60
  # banner_mask_alpha: 0.3
  title: 关于
  subtitle: " "
  avatar: //cravatar.cn/avatar/0047e82c924f776a6405bb59e72445d8?s=960
  name: "Jiecs"
  intro: "废了废了"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/jiesou", tip: "GitHub" }
    - { class: "iconfont icon-bilibili", link: "https://space.bilibili.com/450649625", tip: "哔哩哔哩" }
    - { class: "iconfont icon-telegram", link: "https://t.me/chen_this", tip: "Telegram" }


#---------------------------
# 自定义页
# Custom Page
#
# 通过 hexo new page 命令创建的页面
# Custom Page through `hexo new page`
#---------------------------
page:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 90
  banner_mask_alpha: 0.3
  # 重定向到首页的延迟(毫秒)
  # Delay in redirecting to home page (milliseconds)
  redirect_delay: 5000


#---------------------------
# 友链页
# Links Page
#---------------------------
# links:
  # enable: true
  # banner_img: /img/default.png
  # banner_img_height: 60
  # banner_mask_alpha: 0.3
  # subtitle:
  # 友链的成员项
  # Member item of page
  # items:
  # - {
  #     title: "Fluid Blog",
  #     intro: "主题博客",
  #     link: "https://hexo.fluid-dev.com/",
  #     avatar: "/img/favicon.png"
  #   }
  #   - {
  #     title: "Fluid Docs",
  #     intro: "主题使用指南",
  #     link: "https://hexo.fluid-dev.com/docs/",
  #     avatar: "/img/favicon.png"
  #   }
  #   - {
  #     title: "Fluid Repo",
  #     intro: "主题 GitHub 仓库",
  #     link: "https://github.com/fluid-dev/hexo-theme-fluid",
  #     avatar: "/img/favicon.png"
  #   }
