index:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 20
post:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 20
  default_index_img: "1"
archive:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 20
category:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 20
tag:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 20
about:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 20
links:
  items:
    - title: 阿龙博客
      link: https://alongw.cn
      avatar: https://alongw.cn/icon/logo.jpg
    - title: 翼轸的小站
      link: https://eezhen.com
      avatar: https://pan.eezhen.com/OneDriveCN/%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E7%9B%B8%E5%85%B3/favicon.png
  banner_img_height: 20
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
