links:
  items:
    - title: 阿龙博客
      link: https://alongw.cn
      avatar: https://alongw.cn/icon/logo.jpg
    - title: 翼轸的小站
      link: https://eezhen.com
      avatar: https://pan.eezhen.com/OneDriveCN/%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E7%9B%B8%E5%85%B3/favicon.png