favicon: /images/favicon.png
apple_touch_icon: /images/favicon.png
tab_title_separator: " - "
force_https: false
index:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
post:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 60
  banner_mask_alpha: 0.3
archive:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
category:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
tag:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
about:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
links:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
  items:
    - title: 阿龙博客
      link: https://alongw.cn
      avatar: https://alongw.cn/icon/logo.jpg
