favicon: /images/uploads/jiecs.png
apple_touch_icon: /img/favicon.png
tab_title_separator: " - "
force_https: false

index:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
post:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 60
  banner_mask_alpha: 0.3
archive:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
category:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
tag:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
about:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
links:
  banner_img: https://bingimg.jiecs.workers.dev/?idx=7
  banner_img_height: 30
  banner_mask_alpha: 0.3
  items:
    - title: 阿龙博客
      link: https://alongw.cn
      avatar: https://alongw.cn/icon/logo.jpg
    - title: 翼轸的小站
      link: https://eezhen.com
      avatar: https://pan.eezhen.com/OneDriveCN/%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E7%9B%B8%E5%85%B3/favicon.png
